import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import '../scss/index.scss';

const notoSansJP = Noto_Sans_JP({
  weight: '400',
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className={`${notoSansJP.className} font-noto-sans-jp`}>
        {children}
      </body>
    </html>
  );
}
